force-app/main/default/objects/transaction_list__c/transaction_list__c.object-meta.xml
<CustomObject>
    <label>transaction list</label>
    <nameField>
        <displayFormat>JL-{0000}</displayFormat>
        <label>transaction list Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>transaction lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/transaction_list__c/fields/award_points__c.field-meta.xml
<CustomField>
    <fullName>award_points__c</fullName>
    <label>award points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/transaction_list__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>transaction lists</relationshipLabel>
    <relationshipName>transaction_lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/transaction_list__c/fields/expiry_date__c.field-meta.xml
<CustomField>
    <fullName>expiry_date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>expiry date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/transactionListBatch.cls
public class transactionListBatch implements Database.Batchable<SObject> {
  public Database.queryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(
      [
        SELECT id, award_points__c, contact__c
        FROM transaction_list__c
        WHERE expiry_date__c = yesterday
      ]
    );
  }

  public void execute(
    Database.BatchableContext bc,
    List<transaction_list__c> transactionList
  ) {
    for (transaction_list__c transactions : transactionList) {
      transactions.award_points__c = 0;
    }

    if (!transactionList.isEmpty()) {
      update transactionList;
    }
  }

  public void finish(Database.BatchableContext bc) {
    System.debug('Mission Complete');
  }
}