force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/isactive__c.field-meta.xml
<CustomField>
    <fullName>isactive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/accountTriggerHandler.cls
public class accountTriggerHandler {
    public static void validateContactActiveStatus(Map<Id,account> oldMap,Map<Id,account> newMap) {
            List<ID> accounts = new List<ID>();
            for(Id accountId : newMap.keyset()) {
                if(newMap.get(accountId).active__c == 'No' && oldMap.get(accountId).active__c == 'Yes') {
                    accounts.add(accountId);
                }
            }

            List<aggregateResult> ar = [select accountId from contact where isactive__c = true and accountId in :accounts group by accountId];
            
            for (AggregateResult a : ar) {   
                Id accId = (Id) a.get('AccountId');
                Account ac = newMap.get(accId);
                if (ac != null) {
                    ac.active__c.addError('Account has atleast one active contact!');
                }
            }
    }
}