force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/isactive__c.field-meta.xml
<CustomField>
    <fullName>isactive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandlerTest.cls
@isTest
private class AccountTriggerHandlerTest {
  @isTest
  static void accountWithActiveContactTest() {
    System.Test.startTest();
    contact c = new contact(
      lastname = 'test',
      email = 'acTesttest@gmail.com',
      isactive__c = true
    );

    insert c;
    contact updatedContact = [
      SELECT id, accountid
      FROM contact
      WHERE id = :c.id
    ];

    System.debug(updatedContact);

    account ac = [
      SELECT id, active__c
      FROM account
      WHERE id = :updatedContact.accountid
    ];
    ac.active__c = 'Yes';
    update ac;

    ac.active__c = 'No';
    System.debug(ac);
    Database.saveResult sr = Database.update(ac, false);

    System.Test.stopTest();

    System.assertEquals(false, sr.isSuccess());

    System.assert(
      sr.getErrors()[0]
        .getMessage()
        .contains('Account has atleast one active contact')
    );
  }
}