force-app/main/default/objects/Contact/fields/integration_id__c.field-meta.xml
<CustomField>
    <fullName>integration_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>integration id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/isactive__c.field-meta.xml
<CustomField>
    <fullName>isactive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/opt_out_YRI__c.field-meta.xml
<CustomField>
    <fullName>opt_out_YRI__c</fullName>
    <label>opt out YRI</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>not requested</fullName>
                <default>true</default>
                <label>not requested</label>
            </value>
            <value>
                <fullName>requested</fullName>
            </value>
            <value>
                <fullName>opt out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/transaction_points__c.field-meta.xml
<CustomField>
    <fullName>transaction_points__c</fullName>
    <label>transaction points</label>
    <summarizedField>transaction_list__c.award_points__c</summarizedField>
    <summaryForeignKey>transaction_list__c.Contact__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/yashorgb_integration_config__mdt/yashorgb_integration_config__mdt.object-meta.xml
<CustomObject>
    <label>yashorgb integration config</label>
    <pluralLabel>yashorgb integration</pluralLabel>
</CustomObject>

force-app/main/default/classes/SyncContactQueueable.cls
public class SyncContactQueueable implements Queueable, Database.AllowsCallouts {
  string syncContactQueueableExecute = 'SyncContactQueueable.execute()';

  public List<contactsDTO> updatedContact;

  public SyncContactQueueable(List<Contact> updateContact) {
    List<contactsDTO> mappedData = new List<contactsDTO>();
    for (contact c : updateContact) {
      contactsDTO cDTO = new contactsDTO();
      cDTO.integrationid = c.integration_id__c;
      cDTO.id = c.id;
      cDTO.firstname = c.firstname;
      cDTO.LastName = c.lastname;
      cDTO.isactive = c.isactive__c;
      cDTO.email = c.email;
      cDTO.awardpoints = c.transaction_points__c;
      cDTO.optOutYRI = c.opt_out_YRI__c;
      mappedData.add(cDTO);
    }

    this.updatedContact = mappedData;
  }

  public void execute(QueueableContext qc) {
    if (System.test.isRunningTest()) {
      return;
    }

    try {
      Http http = new Http();
      HttpRequest req = new HttpRequest();

      yashorgb_integration_config__mdt config = yashorgb_integration_config__mdt.getInstance(
        'sync_Contact'
      );
      req.setEndpoint('callout:yashorgb' + config.endpoint__c);
      req.setMethod('POST');
      req.setHeader('Content-Type', 'application/json');
      req.setBody(JSON.serialize(updatedContact));

      HttpResponse res = http.send(req);

      if (res.getStatusCode() != 200) {
        String resultData =
          res.getBody() +
          'status code - ' +
          res.getStatusCode();
        System.enqueueJob(
          new errorLog(resultData, syncContactQueueableExecute)
        );
      }
    } catch (Exception e) {
      System.enqueueJob(new errorLog(e, syncContactQueueableExecute));
      throw e;
    }
  }
}