force-app/main/default/objects/Contact/fields/integration_id__c.field-meta.xml
<CustomField>
    <fullName>integration_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>integration id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/isactive__c.field-meta.xml
<CustomField>
    <fullName>isactive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/opt_out_YRI__c.field-meta.xml
<CustomField>
    <fullName>opt_out_YRI__c</fullName>
    <label>opt out YRI</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>not requested</fullName>
                <default>true</default>
                <label>not requested</label>
            </value>
            <value>
                <fullName>requested</fullName>
            </value>
            <value>
                <fullName>opt out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/transaction_points__c.field-meta.xml
<CustomField>
    <fullName>transaction_points__c</fullName>
    <label>transaction points</label>
    <summarizedField>transaction_list__c.award_points__c</summarizedField>
    <summaryForeignKey>transaction_list__c.Contact__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/syncContact.cls
@RestResource(urlMapping='/syncContact')
global without sharing class syncContact {
  private static final string syncContactsyncContactMethod = 'syncContact.syncContactMethod()';

  private static final Map<String, String> fieldMap = new Map<String, String>{
    'email' => 'email',
    'firstname' => 'firstName',
    'lastname' => 'lastName',
    'awardpoints' => 'transaction_Points__c',
    'isactive' => 'isactive__c',
    'optoutyri' => 'opt_out_YRI__c',
    'integrationid' => 'integration_id__c'
  };

  @HttpPost
  global static void syncContactMethod() {
    try {
      String body = RestContext.request.requestBody.toString();

      List<contactsDTO> dtos = (List<contactsDTO>) JSON.deserialize(
        body,
        List<contactsDTO>.class
      );

      List<Contact> cons = new List<Contact>();

      List<String> sourceContactIds = new List<String>();

      for (contactsDTO dto : dtos) {
        sourceContactIds.add(dto.integrationid);
      }

      Map<String, ID> sourceContactIdMap = new Map<String, ID>();

      for (contact con : [
        SELECT integration_id__c, id
        FROM contact
        WHERE integration_id__c IN :sourceContactIds
      ]) {
        sourceContactIdMap.put(con.integration_id__c, con.id);
      }

      List<contact> contactsToUpdate = new List<contact>();
      List<contact> contactsToInsert = new List<contact>();

      for (contactsDTO dto : dtos) {
        Contact c = new Contact();

        Map<String, Object> dtoMap = (Map<String, Object>) JSON.deserializeUntyped(
          JSON.serialize(dto)
        );

        for (String key : dtoMap.keySet()) {
          Object value = dtoMap.get(key);
          if (fieldMap.containsKey(key) && value != null) {
            c.put(fieldMap.get(key), value);
          }
        }
        System.debug(c);
        System.debug(dtoMap);
        System.debug(sourceContactIdMap);
        if (sourceContactIdMap.containsKey(dto.integrationid)) {
          c.id = (ID) sourceContactIdMap.get(dto.integrationid);
          contactsToUpdate.add(c);
        } else {
          contactsToInsert.add(c);
        }
      }

      if (!contactsToInsert.isEmpty()) {
        insert contactsToInsert;
      } else {
        update contactsToUpdate;
      }
    } catch (Exception e) {
      errorLog.createErrorLog(e, syncContactsyncContactMethod);
      throw e;
    }
  }
}