force-app/main/default/objects/Contact/fields/isactive__c.field-meta.xml
<CustomField>
    <fullName>isactive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/opt_out_YRI__c.field-meta.xml
<CustomField>
    <fullName>opt_out_YRI__c</fullName>
    <label>opt out YRI</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>not requested</fullName>
                <default>true</default>
                <label>not requested</label>
            </value>
            <value>
                <fullName>requested</fullName>
            </value>
            <value>
                <fullName>opt out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/checkForOptOut.cls
public class checkForOptOut {
    /*@Future
    public static void checkIfOptedOut() {
        List<contact> contacts = [select id,opt_out_YRI__c from contact where user__c != null and isactive__c != false and opt_out_YRI__c = 'requested'];
        
        for(contact c : contacts) {
            c.opt_out_YRI__c = 'opt out';
            c.isactive__c = false;
        }
        
        update contacts;
        
    }


    */
}